apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keyword-index-service
  namespace: argocd
spec:
  project: search-engine
  source:
    repoURL: https://github.com/Sanket9326/Distrubuted-Search-Engine.git
    targetRevision: master
    path: deploy/helm/keyword-index-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: search-engine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
