// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace DocumentIngestionService.Persistence.Migrations;

[DbContext(typeof(DocumentIngestionDbContext))]
partial class DocumentIngestionDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Entities.DocumentMetadata", b =>
            {
                b.Property<string>("DocumentId")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<int>("AuthorizedDepartments")
                    .HasColumnType("integer");

                b.Property<string>("ContentType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.Property<DateTime>("IngestedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UploadedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("DocumentId");

                b.ToTable("document_metadata", (string)null);
            });
#pragma warning restore 612, 618
    }
}