{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-ingestion-service.fullname" . }}
  labels:
    {{- include "document-ingestion-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
