// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace KeywordIndexService.Persistence.Migrations;

[DbContext(typeof(KeywordIndexDbContext))]
[Migration("20260802154657_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Entities.DocumentKeywordIndexStatus", b =>
            {
                b.Property<string>("DocumentId")
                    .HasMaxLength(600)
                    .HasColumnType("character varying(600)");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)");

                b.Property<DateTime?>("IndexedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<DateTime>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("DocumentId");

                b.ToTable("keyword_index_status", (string)null);
            });

        modelBuilder.Entity("Entities.IndexPosting", b =>
            {
                b.Property<int>("TermId")
                    .HasColumnType("integer");

                b.Property<Guid>("ChunkId")
                    .HasColumnType("uuid");

                b.Property<string>("DocumentId")
                    .IsRequired()
                    .HasMaxLength(600)
                    .HasColumnType("character varying(600)");

                b.PrimitiveCollection<int[]>("Positions")
                    .IsRequired()
                    .HasColumnType("integer[]");

                b.Property<int>("TermFrequency")
                    .HasColumnType("integer");

                b.HasKey("TermId", "ChunkId");

                b.HasIndex("ChunkId");

                b.HasIndex("DocumentId");

                b.ToTable("index_postings", (string)null);
            });

        modelBuilder.Entity("Entities.IndexTerm", b =>
            {
                b.Property<int>("TermId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TermId"));

                b.Property<int>("DocumentFrequency")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0);

                b.Property<string>("Term")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("TermId");

                b.HasIndex("Term")
                    .IsUnique();

                b.ToTable("index_terms", (string)null);
            });

        modelBuilder.Entity("Entities.IndexPosting", b =>
            {
                b.HasOne("Entities.IndexTerm", null)
                    .WithMany()
                    .HasForeignKey("TermId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
