apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "embedding-service.fullname" . }}
  labels:
    {{- include "embedding-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "embedding-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "embedding-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: embedding-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- if or .Values.config .Values.secrets }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ include "embedding-service.fullname" . }}
            {{- end }}
            {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "embedding-service.fullname" . }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
